[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "narumii"
version = "0.2.0"
authors = [
  { name="Yufei Wu", email="yufei.wu@cec.mpg.de" },
]
description = "NaRuMii, a personalized toolbox for NMR data analysis. 笑顔になるなる :)"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["numpy>=2.0","scipy>=1.15","matplotlib>=3.9"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/yufewu/narumi"
Issues = "https://github.com/yufewu/narumi/issues"